name: docs-query-tool

services:
  db:
    image: pgvector/pgvector:pg18
    restart: unless-stopped
    env_file: 
      - path: .env
        required: true
    volumes:
      - pgdata:/var/lib/postgresql   
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro  
    ports:
      - "5432:5432"
    profiles:
      - database_access
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    expose:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama   
 
  query:
    build: 
      context: .
      dockerfile: query/Dockerfile
    depends_on:
      db:                         
        condition: service_healthy
      ollama:
        condition: service_started
    env_file: 
      - path: .env
        required: true   
    profiles:
      - database_access 
    volumes:
      - ./app:/src/app 
    
  embed:
    build: 
      context: .
      dockerfile: embed/Dockerfile
    ports:
      - "5000:5000"
    env_file: 
      - path: embed.env
        required: true    
    volumes:
      - ./embed:/app/embed
      - embed_data:/app/data
    profiles:
      - embed
    tty: true

  migrate:
    build: 
      context: .
      dockerfile: migrate/Dockerfile
    ports:
      - "5001:5001"
    env_file: 
      - path: migrate.env
        required: true    
    volumes:
      - ./migrate:/app/migrate
      - embed_data:/app/data
    profiles:
      - database_access
    depends_on:
      db:
        condition: service_healthy
    tty: true

volumes:
  ollama_data:
  pgdata:
  embed_data:
